sync

diff --git a/bin/.local/bin/envy b/bin/.local/bin/envy
--- a/bin/.local/bin/envy
+++ b/bin/.local/bin/envy
@@ -1,15 +1,73 @@
 #!/usr/bin/env bash
-# $ alias envy="source ~/Workspace/repos/scratchpad/envy/envy.sh"
+
+usage() {
+    cat 1>&2 <<EOF
+envy
+Subshell spawner for Python
+
+This utility searched the current directory for a virtual environment
+in the current directory, travels up the directory tree (up to the
+users home directory) until a virtual env is found, then spawns a
+subshell that sources '.bashrc' and the virtual environment (and sets
+a value for 'ENVY').
+
+By default, searches for a virtual environment called '.venv', can be
+specified in the first argument.
+
+If a virtual environment is not found, a new virtual environment is
+created at the current directory and a subshell is invoked.
+
+USAGE:
+    codehelp [OPTIONS] [NAME]
+
+ARGS:
+    NAME              Virtual env to search/create (default: '.venv')
+
+OPTIONS:
+    -h, --help                                     Show documentation
+    -n, --new         Skip search and create/activate new virtual env
+EOF
+}
 
 main() {
-    if ! [ -z "${VIRTUAL_ENV}" ]; then
-        echo "Deactivating venv (${VIRTUAL_ENV})"
-        deactivate
-        return 0
-    fi
 
     local venv_name
     venv_name=${1:-.venv}
+
+    for arg in "$@"; do
+        case "$arg" in
+            --help)
+                usage
+                return 0
+                ;;
+            --new)
+                new_venv ${venv_name}
+                return 0
+                ;;
+            *)
+                while getopts :hn sub_arg "$arg"; do
+                    case "$sub_arg" in
+                        h)
+                            usage
+                            return 0
+                            ;;
+                        n)
+                            new_venv ${venv_name}
+                            return 0
+                            ;;
+                        *)
+                            ;;
+                        esac
+                done
+                ;;
+        esac
+    done
+
+    # Check envy var and exit subshell
+    if [ ! -z "${ENVY}" ]; then
+        echo "Already set venv (${VIRTUAL_ENV}), exit to deactivate."
+        exit 0
+    fi
 
     local selected_dir
     local venv_dir
@@ -22,22 +80,31 @@ main() {
         venv_dir="${selected_dir}/${venv_name}"
         if [ -d "${venv_dir}" ]; then
             echo "Found ${venv_dir}"
-            source "${venv_dir}/bin/activate"
-            return 0
+            break
         fi
         selected_dir=$(dirname ${selected_dir})
     done
 
-    echo "Couldn't find a venv named ${venv_name}, creating one in current directory"
-    python -m venv ${venv_name}
-    venv_dir="$(pwd)/${venv_name}"
-    source "${venv_dir}/bin/activate"
+    if [ -z "${venv_dir}" ]; then
+        echo "Couldn't find a venv named ${venv_name}, creating one in current directory"
+        new_venv ${venv_name}
+        venv_dir="$(pwd)/${venv_name}"
+    fi
+
+    venv_subshell "${venv_dir}"
     return 0
+}
+
+new_venv() {
+    python -m venv ${venv_name}
+}
+
+venv_subshell() {
+    bash --init-file <(echo "source ${1}/bin/activate; export ENVY=1" | cat ~/.bashrc -) -i
 }
 
 dir_depth() {
     echo "${1}" | grep -o "/" | wc -l
 }
 
-main "$@" || exit 1
-
+main "$@"
